// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANetHI_IwHpV0F6YbjQ1AdgXcErNhr1ig',
    appId: '1:241214364644:web:e827111c640637932d05f1',
    messagingSenderId: '241214364644',
    projectId: 'countdown-sample',
    authDomain: 'countdown-sample.firebaseapp.com',
    storageBucket: 'countdown-sample.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt7OE9lhpoSHxOe4lVQwYIDBJOtTi_V5M',
    appId: '1:241214364644:android:93115f0c3ef543eb2d05f1',
    messagingSenderId: '241214364644',
    projectId: 'countdown-sample',
    storageBucket: 'countdown-sample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoL1jaIZ-qDmKtArQblWwU3wKpoY5MawU',
    appId: '1:241214364644:ios:15f0aeb71146c38f2d05f1',
    messagingSenderId: '241214364644',
    projectId: 'countdown-sample',
    storageBucket: 'countdown-sample.appspot.com',
    iosBundleId: 'com.example.countdownApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoL1jaIZ-qDmKtArQblWwU3wKpoY5MawU',
    appId: '1:241214364644:ios:38ab78cea4a5080b2d05f1',
    messagingSenderId: '241214364644',
    projectId: 'countdown-sample',
    storageBucket: 'countdown-sample.appspot.com',
    iosBundleId: 'com.example.countdownApp.RunnerTests',
  );
}
